version: 2
jobs:
  build-with-docker:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./build-image-target.sh

  # See https://circleci.com/docs/2.0/using-shell-scripts/#shell-script-best-practices
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources

workflows:
  version: 2
  build-stuff:
    jobs:
      - build-with-docker:
          filters:
            branches:
              only:
                - master
                - /pull\/.*/
      - shellcheck:
          filters:
            branches:
              only:
                - master
                - /pull\/.*/
